language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - grunt test
  - grunt build

deploy:
  all_branches: true
  skip_cleanup: true
  strategy: api
  provider: heroku
  api_key:
    secure: ZylRRG3s+kRTTKsD2bbhDDUDHrUDNuFMXHq0o5iJcD/rLruygtkdmW/qyTgZUu/Ee6pvmcTiTkj7e8ekCXLtURARFnMGr9jI13MlQizXZLN0YuHnrQQoNmEi4H5uYs3zpcoD3t5OgZ5oiHkkKavcfQ8ljFwoTfo7ujSGr6k5r+E=
  app: tessellate-app
  on:
    repo: Wildhoney/Tessellate